export const AUTH_ATTEMPTING = 'AUTH_ATTEMPTING';
export const AUTH_SUCCESS    = 'AUTH_SUCCESS';
export const AUTH_FAILED     = 'AUTH_FAILED';
export const LOGOUT          = 'LOGOUT';
export const AUTH_PROFILE    = 'AUTH_PROFILE';
export const SIGNUP_SUCCESS  = 'SIGNUP_SUCCESS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SUB_QUANTITY = 'SUB_QUANTITY';
export const ADD_QUANTITY = 'ADD_QUANTITY';
export const ADD_SHIPPING = 'ADD_SHIPPING';

export const FETCHING_PRODUCT           = 'FETCHING_PRODUCT';
export const FETCHING_PRODUCT_SUCCESS   = 'FETCHING_PRODUCT_SUCCESS';
export const FETCHING_PRODUCT_FAILED    = 'FETCHING_PRODUCT_FAILED';